<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <nullable>enable</nullable>
    <Version>1.0.2</Version>
    <Description>Helper to read from Kafka that allows for parallelism</Description>
    <Copyright>MIT</Copyright>
    <PackageProjectUrl>https://github.com/MarcinGajda36/Kafka</PackageProjectUrl>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.12.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
  </ItemGroup>

</Project>
