<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <DebugType>embedded</DebugType>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>Marcin Gajda</Authors>
    <Description>
      At least once delivery kafka client, that makes parallel processing easier.
      Starting point is static method: Magj.Kafka.KafkaClient.AtLeastOnceAsync(...);
    </Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>1.0.3</Version>
    <Copyright>MIT</Copyright>
    <PackageProjectUrl>https://github.com/MarcinGajda36/Kafka</PackageProjectUrl>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.12.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
  </ItemGroup>

</Project>